# Generated by Django 3.2.5 on 2021-07-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
